### ISSUE TITLE
Add a LICENSE to repo. 

### ISSUE THREAD

**Issue by plugxor** [OTRF/2021-OceanLotus-workshop#9]
I usually do the MIT license - Ben
OTR uses GPLv3, confirm with Roberto the use @plugxor

**Comment by plugxor** [comment]
Spoke with @Cyb3rWard0g regarding this issue. We can use the license that best fits our needs.

**Comment by cat-alyst** [comment]
I recommend an MIT, BSD, or apache based licence. It's more open.

**Comment by cat-alyst** [comment]
FYI 
I'm releasing my portion of this work from MITRE under the MIT license.

**Comment by CptOfEvilMinions** [comment]
MIT License added

https://github.com/OTRF/macos-workshops/blob/main/LICENSE
https://github.com/OTRF/macos-workshops/pull/34
